<?php
/** @var \Meetup\Entity\Meetup $meetup */
$meetup = $this->meetup;
?>
<div class="row">
    <div class="col-xs-12">
        <h1>View Meetup</h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $meetup->getTitle(); ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php echo $meetup->getDescription(); ?>
                </p>
                <hr>
                <p class="text-center">
                    <?php $meetup->getStartAt(); ?> - <?php $meetup->getEndAt(); ?>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="text-left">
            <a href="<?php echo $this->url('home'); ?>">
                <button type="button" class="btn btn-default">Back to the list</button>
            </a>
        </div>
    </div>
</div>