<div class="row">
    <div class="col-xs-12">
        <h1>List of meetup</h1>
    </div>
</div>
<div class="row">
    <?php foreach ($this->meetups as $meetup): /** @var \Meetup\Entity\Meetup $meetup */ ?>
        <div class="col-xs-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $meetup->getTitle(); ?>  </h3>
                </div>
                <div class="panel-body">
                    <p>
                        <?php echo $meetup->getDescription(); ?>
                    </p>
                    <div class="text-right">
                        <a href="<?php echo $this->url('meetups/view', ['id' => $meetup->getId()]); ?>">
                            <button type="button" class="btn btn-default">Details</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="text-right">
            <a href="<?php echo $this->url('meetups/new'); ?>">
                <button type="button" class="btn btn-default">Add new meetup</button>
            </a>
        </div>
    </div>
</div>