<div class="row">
    <div class="col-xs-12">
        <h1>New meetup</h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="text-right">
            <a href="<?php echo $this->url('home'); ?>">
                <button type="button" class="btn btn-default">Back to the list</button>
            </a>
            <a href="<?php echo $this->url('new'); ?>">
                <button type="button" class="btn btn-primary">Create meetup</button>
            </a>
        </div>
    </div>
</div>